### ISSUE TITLE
Resolve outlet channel migration and position tracking:

### ISSUE THREAD

**Issue by RegMeasures** [RegMeasures/HapuaModel#7]
- [x] update centreline position when sed deposited on 1 bank due to LST or overwash
- [x] update outlet channel end position when needed due to centreline moving (or shoreline/lagoon) or width changing.
- [x] allow channel truncation
